# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(default='static/img/no-img.jpg', upload_to='MyBlog/static/img/Blog/')),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyUser.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyUser.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The topic is not specified!', max_length=200)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('text', models.TextField(blank=True, default='Text not written!')),
                ('summary', models.TextField(default='Summary not written!')),
                ('image', models.ImageField(default='MyBlog/static/img/no-img.jpg', upload_to='MyBlog/static/img/post/')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Post'),
        ),
    ]
