# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20170706_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summery',
            field=models.TextField(default='Summary not written!'),
        ),
    ]
