# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0006_auto_20170707_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
