# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0007_remove_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auther',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to='MyBlog.User'),
        ),
    ]
