# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
        ('MyBlog', '0012_auto_20170707_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyUser.MyUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='auther',
        ),
        migrations.AlterField(
            model_name='comment',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyUser.MyUser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 7, 20, 29, 34, 89720, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 7, 20, 29, 34, 87221, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='Text not written!'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(to='MyBlog.Post'),
        ),
    ]
