# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0013_auto_20170708_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 19, 43, 3, 167265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 19, 43, 3, 164765, tzinfo=utc)),
        ),
    ]
