# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0014_auto_20170709_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 9, 4, 46, 27, 937300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 9, 4, 46, 27, 935736, tzinfo=utc)),
        ),
    ]
