# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0017_auto_20170712_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
