# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 19, 43, 3, 161263, tzinfo=utc)),
        ),
    ]
