# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0002_auto_20170709_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 9, 4, 46, 27, 932794, tzinfo=utc)),
        ),
    ]
