# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 04:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_auto_20170709_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 9, 4, 48, 33, 479910, tzinfo=utc)),
        ),
    ]
