# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0005_auto_20170709_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='time',
        ),
    ]
