# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='First name is not specified', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/img/no-img.jpg', upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='summery',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='The topic is not specified!', max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='auther',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='auther',
            field=models.OneToOneField(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to='MyBlog.User'),
        ),
    ]
