# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0011_auto_20170707_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default='Thu Jul  6 22:02:39 2017'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default='Thu Jul  6 22:02:39 2017'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default='Thu Jul  6 22:02:39 2017'),
        ),
    ]
