# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0016_auto_20170709_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posts',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='static/img/no-img.jpg', upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyUser.MyUser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyUser.MyUser'),
        ),
    ]
