# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0018_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='number',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='static/img/no-img.jpg', upload_to='static/img/Blog/'),
        ),
    ]
