# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0019_auto_20170714_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/img/no-img.jpg', upload_to='static/img/post/'),
        ),
    ]
