# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0021_auto_20170714_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summery',
            new_name='summary',
        ),
    ]
